version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/home/apps/hyperX
      - /home/smart8099/hyperX_system/db.sqlite3:/home/apps/hyperX/db.sqlite3
    env_file:
      - .env  
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000